### ISSUE TITLE
Not working with Node 10.8.0

### ISSUE THREAD

**Issue by Jvst1n** [agebrock/tunnel-ssh#70]
Hi,

I have encountered an issue when using our package with node 10.8.0. I got this error:

```
D:\Code\Node JS\braces-easy-way\node_modules\ssh-tunnel\node_modules\require-dir\index.js:93
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (D:\Code\Node JS\braces-easy-way\node_modules\require-dir\index.js:93:37)
    at new App (D:\Code\Node JS\braces-easy-way\node_modules\ssh-tunnel\lib\app.js:38:19)
    at Object.<anonymous> (D:\Code\Node JS\braces-easy-way\node_modules\ssh-tunnel\lib\app.js:26:28)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)

```
I did research a lot, but couldn't solve this problem.
So anyone has any solutions?
Thank you guys for helping and creating a wonderful package.

**Comment by Jvst1n** [comment]
Oh, I installed wrong package, ssh-tunnel instead of tunnel-ssh. Sorry about that, but I still got this warning:

(node:15920) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by agebrock** [comment]
Please add in what file the issue occurs. I am not able to reproduce it.

**Comment by slyadams** [comment]
I think this is because tunnel-ssh requires version ssh2 version 0.5.4, which in turn requires ssh2-streams 0.1.5. ssh2-streams at this version uses the old Buffer constructor. The solution seems to be to bump the ssh2 version.

**Comment by agebrock** [comment]
We updated ssh2 to most recent version. let me know if you face any further issues.
